"""Utility modules for the CC statement parser."""

from .currency_parser import (
    compare_amounts,
    extract_amounts_from_text,
    format_currency_indian,
    format_in_crores,
    format_in_lakhs,
    is_valid_amount,
    parse_currency,
    parse_currency_strict,
)
from .date_parser import (
    extract_dates_from_text,
    format_date_indian,
    get_financial_year,
    is_valid_date_string,
    parse_date,
    parse_date_range,
    parse_date_strict,
)
from .exceptions import (
    CCParserError,
    ConfigurationError,
    ConfidenceThresholdError,
    DatabaseError,
    ExtractionError,
    FileError,
    IssuerNotSupportedError,
    OCRError,
    ParsingError,
    ProcessingError,
    SecurityError,
    StorageError,
    TimeoutError,
    ValidationError,
)
from .file_utils import (
    check_pdf_has_text,
    ensure_directory,
    get_file_hash,
    get_file_info,
    get_pdf_page_count,
    get_unique_filename,
    is_pdf_scanned,
    safe_filename,
    validate_file_extension,
    validate_file_size,
    validate_pdf_file,
)
from .logger import (
    clear_request_id,
    get_logger,
    get_request_id,
    log_with_context,
    set_request_id,
    setup_logging,
)
from .security import (
    extract_card_number,
    get_card_type,
    mask_account_number,
    mask_card_number,
    mask_email,
    mask_name,
    mask_phone_number,
    mask_text_pattern,
    redact_pii,
    sanitize_for_logging,
    validate_card_number_luhn,
)

__all__ = [
    # Exceptions
    "CCParserError",
    "ParsingError",
    "ValidationError",
    "OCRError",
    "FileError",
    "ExtractionError",
    "StorageError",
    "DatabaseError",
    "ConfigurationError",
    "ProcessingError",
    "SecurityError",
    "TimeoutError",
    "IssuerNotSupportedError",
    "ConfidenceThresholdError",
    # Logger
    "setup_logging",
    "get_logger",
    "set_request_id",
    "clear_request_id",
    "get_request_id",
    "log_with_context",
    # Date parser
    "parse_date",
    "parse_date_strict",
    "extract_dates_from_text",
    "format_date_indian",
    "parse_date_range",
    "is_valid_date_string",
    "get_financial_year",
    # Currency parser
    "parse_currency",
    "parse_currency_strict",
    "extract_amounts_from_text",
    "format_currency_indian",
    "format_in_lakhs",
    "format_in_crores",
    "is_valid_amount",
    "compare_amounts",
    # File utils
    "validate_file_extension",
    "validate_file_size",
    "get_file_hash",
    "validate_pdf_file",
    "get_pdf_page_count",
    "check_pdf_has_text",
    "is_pdf_scanned",
    "ensure_directory",
    "safe_filename",
    "get_unique_filename",
    "get_file_info",
    # Security
    "mask_card_number",
    "mask_account_number",
    "mask_email",
    "mask_phone_number",
    "mask_name",
    "redact_pii",
    "extract_card_number",
    "validate_card_number_luhn",
    "get_card_type",
    "sanitize_for_logging",
    "mask_text_pattern",
]
