"""Pydantic schemas for the CC statement parser."""

from .internal import (
    BatchProcessingJob,
    CacheEntry,
    ExtractionAttempt,
    ExtractionMetrics,
    FieldExtractionContext,
    IssuerDetectionResult,
    OCRResult,
    PatternMatch,
    PDFMetadata,
    ProcessingOptions,
    ProcessingPipeline,
    ProcessingStep,
    StorageLocation,
    SystemMetrics,
    TableExtractionResult,
    TextExtractionResult,
    ValidationResult,
)
from .request import (
    BulkParseRequest,
    CancelJobRequest,
    FilterRequest,
    HealthCheckRequest,
    JobStatusRequest,
    ParseRequest,
    ResultRequest,
    RetryJobRequest,
)
from .response import (
    BulkParseResponse,
    DocumentResponse,
    ErrorResponse,
    ExtractionResultResponse,
    FieldResponse,
    HealthCheckResponse,
    JobResponse,
    ListJobsResponse,
    ListResultsResponse,
    MessageResponse,
    StatsResponse,
    UploadResponse,
)

__all__ = [
    # Request schemas
    "ParseRequest",
    "JobStatusRequest",
    "ResultRequest",
    "FilterRequest",
    "RetryJobRequest",
    "CancelJobRequest",
    "BulkParseRequest",
    "HealthCheckRequest",
    # Response schemas
    "FieldResponse",
    "DocumentResponse",
    "JobResponse",
    "ExtractionResultResponse",
    "UploadResponse",
    "ErrorResponse",
    "HealthCheckResponse",
    "ListJobsResponse",
    "ListResultsResponse",
    "BulkParseResponse",
    "StatsResponse",
    "MessageResponse",
    # Internal DTOs
    "PDFMetadata",
    "TextExtractionResult",
    "OCRResult",
    "IssuerDetectionResult",
    "FieldExtractionContext",
    "ExtractionMetrics",
    "ValidationResult",
    "ProcessingOptions",
    "StorageLocation",
    "CacheEntry",
    "ProcessingStep",
    "ProcessingPipeline",
    "TableExtractionResult",
    "PatternMatch",
    "ExtractionAttempt",
    "BatchProcessingJob",
    "SystemMetrics",
]
